# Build docker image for pull requests, but do not submit back to hub.

trigger:
- master

jobs:
- job: Test_Build_Linux
  pool:
    vmImage: 'ubuntu-16.04'
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master')) #not master
  variables:
    imageName: 'jhardison/nodeverify:linux$(build.buildId)'
    imageLatest: 'jhardison/nodeverify:latestlinux'
  steps:
  - script: docker build -f Dockerfile.linuxamd64 -t $(imageName) .
    displayName: 'docker build'
  - task: Docker@1
    displayName: Tag image
    inputs:
      command: tag
      imageName: $(imageName)
      arguments: $(imageLatest)

- job: Test_Build_Windows
  pool:
    vmImage: 'vs2017-win2016'
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master')) #not master
  variables:
    imageName: 'jhardison/nodeverify:windows$(build.buildId)'
    imageLatest: 'jhardison/nodeverify:latestwindows'
  steps:
  - script: docker build -f Dockerfile.windowsamd64 -t $(imageName) .
    displayName: 'docker build'
  - task: Docker@1
    displayName: Tag image
    inputs:
      command: tag
      imageName: $(imageName)
      arguments: $(imageLatest)