# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  variables:
    imageName: 'jhardison/nodeverify:$(build.buildId)'
  steps:
  - script: docker build -f Dockerfile -t $(imageName) .
    displayName: 'docker build'

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  variables:
    imageName: 'jhardison/nodeverify:$(build.buildId)'
  steps:
  - script: docker build -f Dockerfile.windows -t $(imageName) .
    displayName: 'docker build'