# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  variables:
    imageName: 'jhardison/nodeverify:linux$(build.buildId)'
    imageLatest: 'jhardison/nodeverify:latest'
  steps:
  - task: Docker@1
    displayName: Build image
    inputs:
      command: build
      dockerFile: Dockerfile
      imageName: $(imageName)
  - task: Docker@1
    displayName: Tag image
    inputs:
      command: tag
      imageName: $(imageName)
      arguments: $(imageLatest)
  - task: Docker@1
    displayName: Container registry login
    inputs:
      command: login
      containerregistrytype: Container Registry
      dockerRegistryEndpoint: JHARDISONDockerHub
  - task: Docker@1
    displayName: Push image
    inputs:
      command: push
      imageName: $(imageName)
  - task: Docker@1
    displayName: Push image
    inputs:
      command: push
      imageName: $(imageLatest)

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  variables:
    imageName: 'jhardison/nodeverify:windows$(build.buildId)'
    imageLatest: 'jhardison/nodeverify:latest'
  steps:
  - task: Docker@1
    displayName: Build image
    inputs:
      command: build
      dockerFile: Dockerfile
      imageName: $(imageName)
  - task: Docker@1
    displayName: Tag image
    inputs:
      command: tag
      imageName: $(imageName)
      arguments: $(imageLatest)
  - task: Docker@1
    displayName: Container registry login
    inputs:
      command: login
      containerregistrytype: Container Registry
      dockerRegistryEndpoint: JHARDISONDockerHub
  - task: Docker@1
    displayName: Push image
    inputs:
      command: push
      imageName: $(imageName)
  - task: Docker@1
    displayName: Push image
    inputs:
      command: push
      imageName: $(imageLatest)
        