# NodeVerify
# used in a poc of various orchestrators to test generic performance and overhead
FROM stefanscherer/node-windows
LABEL maintainer="jmh@jonathanhardison.com"

# ExpressJS Listener
EXPOSE 3005
